sudo: false
dist: bionic
language: node_js
git:
  depth: 3
node_js:
  - "10"
script:
  - npm test
  - npm run eslint
  - commitlint-travis
cache:
  directories:
    - node_modules
notifications:
  slack: indec-sistemas:U34T7wkSbzuMWCcXIw9DOY05
